spring:
    application:
        name: spring-security-jwt
    datasource:
        url: jdbc:mysql://${DB_HOST:localhost:3306}/${DB_NAME:spring_security_jwt}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${DB_USER:root}
        password: ${DB_PASS:root}
        driver-class-name: com.mysql.cj.jdbc.Driver
    output:
        ansi:
            enabled: always